import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { FileText, ExternalLink, Code2 } from "lucide-react";
import { projects, person } from "@/lib/portfolio";
import { details, type CaseSlug } from "@/lib/project-details";
import { PageFrame, TechStack } from "@/components/portfolio-layout";
import { ProjectMark, ProjectArchitecture, CaseNotebook, PipelineExplorer, ResearchComparison } from "@/components/portfolio-interactions";

export function generateStaticParams(){return projects.map(project=>({slug:project.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)return {title:"Project not found",robots:{index:false,follow:false}};return {title:`${p.name} — ${p.type}`,description:p.description,alternates:{canonical:`/projects/${p.slug}`},openGraph:{title:`${p.name} | ${person.name}`,description:p.description,url:`${person.origin}/projects/${p.slug}`,type:"website"},twitter:{card:"summary",title:`${p.name} | ${person.name}`,description:p.description}};}
const metrics:Record<string,{value:string;label:string}[]>={navox:[{value:"2,820",label:"API regression tests"},{value:"437",label:"Web tests in reviewed CI"},{value:"8",label:"Extension tests in reviewed CI"}],fluxion:[{value:"72",label:"CPU/native tests passed"},{value:"5 / 5",label:"PyTorch reference reports"},{value:"2,000",label:"Retained timing samples"}],marketlab:[{value:"3,000",label:"Verified jobs in three local runs"},{value:"39.96 /s",label:"Combined local throughput"},{value:"319.77 ms",label:"Client-observed local p99"}],modelforge:[{value:"164",label:"Tests passed in recorded CI"},{value:"3",label:"Recorded test skips"},{value:"SHA-256",label:"Immutable artifact identity"}],toolret:[{value:"23.4%",label:"Fewer cross-encoder calls"},{value:"1,500",label:"Untouched confirmation queries"},{value:"37,292",label:"Tools in the retrieval catalog"}]};
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();const d=details[p.slug as CaseSlug];const current=projects.findIndex(p=>p.slug===slug);const next=projects[(current+1)%projects.length];const pdf=d.resources.find(r=>r.kind==="pdf")!;
 const overview=<><div className="notebook-heading"><span className="mono">THE IDEA</span><h2>What {p.name} does.</h2><p>{d.overview}</p></div><div className="feature-grid">{d.features.map(f=><article key={f.title}><h3>{f.title}</h3><p>{f.text}</p></article>)}</div><section className="built-with"><div className="section-heading"><span className="mono">BUILT WITH</span><h2>The technology.</h2></div><TechStack technologies={d.technologies}/></section></>;
 const system=<><div className="notebook-heading"><span className="mono">FROM INPUT TO OUTCOME</span><h2>How it works.</h2><p>{d.problem}</p></div><PipelineExplorer steps={d.stages} name={p.name}/>{p.slug==="marketlab"?<figure className="pipeline-figure"><img src="/projects/marketlab-stock-pipeline.svg" width={1600} height={950} loading="lazy" alt="MarketLab stock-data pipeline: Alpha Vantage and CSV imports validate into owner-scoped price snapshots; saved backtests can branch into verification or reviewed sharing."/><figcaption>Stock imports and verification paths from the repository architecture diagram.</figcaption></figure>:p.slug==="modelforge"?<ProjectArchitecture project={p}/>:null}<div className="section-heading decisions-heading"><span className="mono">ENGINEERING DECISIONS</span><h2>Why it’s built this way.</h2></div><div className="decision-grid">{d.decisions.map(f=><article key={f.title}><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></>;
 const evidence=<><div className="notebook-heading"><span className="mono">RECORDED CHECKPOINTS</span><h2>What the evidence shows.</h2><p>{d.evidence}</p></div><div className="metric-grid">{metrics[p.slug].map(m=><div key={m.label}><strong>{m.value}</strong><span>{m.label}</span></div>)}</div>{p.slug==="toolret"?<div className="evidence-visual"><ResearchComparison/></div>:p.slug==="navox"?<figure className="evidence-visual"><video className="case-video" controls preload="none" poster="/projects/navox.jpg" aria-label="NavoX sample-data interface walkthrough"><source src="/projects/navox-walkthrough.mp4" type="video/mp4"/>Your browser does not support video. <a href="/projects/navox-walkthrough.mp4">Open the walkthrough</a>.</video><figcaption>A 48-second silent interface tour using authored sample data.</figcaption></figure>:p.slug==="fluxion"?<div className="fluxion-evidence"><figure><img src="/projects/fluxion.png" alt={p.imageAlt} width={1400} height={800} loading="lazy"/><figcaption>Complete training-step measurements from the October 4 Linux CPU run.</figcaption></figure><figure><img src="/projects/fluxion-autograd.png" alt="For y = x*x + x at x = 3, shared-input gradient contributions 3 + 3 + 1 sum to 7." width={1400} height={980} loading="lazy"/><figcaption>Shared-input gradient accumulation, with a derivative you can check.</figcaption></figure></div>:p.slug==="modelforge"?<div className="release-proof"><span className="mono">RECORDED VALIDATION SCENARIO</span><div>{["Serve v1","Canary v2","Promote v2","Restore v1","Abort regressed v3"].map(s=><span key={s}>{s}</span>)}</div><p>v1 remains authoritative after the deliberately failed canary.</p></div>:null}<div className="scope-panel"><span className="mono">SCOPE & LIMITS</span><p>{d.scope}</p></div><a href={pdf.href} className="text-link" target="_blank" rel="noopener noreferrer">{p.slug==="toolret"?"Read the full research PDF":"Read the engineering brief PDF"}</a></>;
 const resources=<><div className="notebook-heading"><span className="mono">OPEN THE WORK</span><h2>Code, documents & proof.</h2><p>{p.slug==="toolret"?"Read the original study and inspect the code, frozen evaluation, and audit.":"A concise engineering brief and direct links to the implementation and supporting evidence."}</p></div><div className="document-feature"><div className="document-cover"><FileText size={40}/><span className="mono">{p.slug==="toolret"?"RESEARCH STUDY":"ENGINEERING BRIEF"}</span><strong>{p.name}</strong><span>Michael Baffour Awuah · 2026</span></div><div><h3>{p.slug==="toolret"?"The original ToolRet study":"Inside the engineering"}</h3><p>{p.slug==="toolret"?"The original confirmation report is available as a PDF, unchanged from the research repository.":"A two-page project brief covering the purpose, workflow, design decisions, recorded checks, and limits."}</p><div className="hero-actions"><a href={pdf.href} className="button-primary" target="_blank" rel="noopener noreferrer">Read PDF</a><a href={pdf.href} className="button-secondary" download>Download PDF</a></div></div></div><div className="resource-grid">{d.resources.filter(r=>r.kind!=="pdf").map(r=><a key={r.href} href={r.href} target="_blank" rel="noopener noreferrer"><span className="mono">{r.kind}</span><strong>{r.label}</strong><ExternalLink size={19}/></a>)}</div></>;
 return <PageFrame className={`case-shell accent-${p.accent}`}><div className="case-breadcrumb"><a href={p.slug==="toolret"?"/research":"/work"}>{p.slug==="toolret"?"Research":"All projects"}</a><span>/ {p.name}</span></div><section className="case-hero"><div className="case-hero-copy"><div className="case-brandline"><ProjectMark slug={p.slug} name={p.name}/><span className="mono">{d.label}</span></div><h1>{p.name}<span>.</span></h1><h2>{d.tagline}</h2><p>{p.description}</p><div className="hero-actions">{p.live?<a className="button-primary" href={p.live} target="_blank" rel="noopener noreferrer">Open {p.name}<ExternalLink size={16}/></a>:<a className="button-primary" href={p.repo} target="_blank" rel="noopener noreferrer"><Code2 size={18}/>Explore source</a>}<a className="button-secondary" href={pdf.href} target="_blank" rel="noopener noreferrer"><FileText size={17}/>{p.slug==="toolret"?"Research PDF":"Project brief"}</a>{p.live?<a className="text-link" href={p.repo} target="_blank" rel="noopener noreferrer">GitHub source</a>:null}</div></div><div className="case-hero-visual"><div className="visual-toolbar"><span className="mono">{p.slug==="navox"?"NAVOX / SAMPLE INTERFACE":p.slug==="fluxion"?"FLUXION / MEASURED CPU RUN":p.slug==="marketlab"?"MARKETLAB / HISTORICAL PRICES":p.slug==="toolret"?"TOOLRET / CONFIRMATION":"MODELFORGE / RELEASE CONTROL"}</span><span className="window-controls" aria-hidden="true"><i/><i/><i/></span></div>{p.image?<img src={p.image} alt={p.imageAlt} width={1400} height={800} fetchPriority="high"/>:p.slug==="toolret"?<div className="case-hero-research"><strong>23.4<span>%</span></strong><p>fewer cross-encoder calls</p><ResearchComparison/></div>:<ProjectArchitecture project={p}/>}<div className="visual-bottomline"><span>{p.evidence}</span><span>{p.slug==="marketlab"?"LOCAL WORKLOAD":p.slug==="toolret"?"1,500 QUERIES":"RECORDED CHECKPOINT"}</span></div></div></section><CaseNotebook overview={overview} system={system} evidence={evidence} resources={resources}/><nav className="case-next" aria-label="More projects"><a href="/work">All projects</a><a href={`/projects/${next.slug}`}><ProjectMark slug={next.slug} name={next.name}/><span>Next project<strong>{next.name}</strong></span></a></nav></PageFrame>;
}
