"""Preserve the light palette while giving legacy CSS literals explicit night equivalents."""
from pathlib import Path
import re,colorsys
palette={}
hex_re=re.compile(r'#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{4}\b|#[0-9a-fA-F]{3}\b')
def adapt(h,role):
 raw=h[1:].lower()
 if len(raw) in (3,4):raw=''.join(c*2 for c in raw)
 alpha=raw[6:];rgb=tuple(int(raw[i:i+2],16)/255 for i in (0,2,4));hue,light,sat=colorsys.rgb_to_hls(*rgb)
 if role=='fg':
  if light>=.80:return '#'+raw
  light=.90 if light<.28 else .76
  sat=min(sat,.68)
 elif role=='line':
  light=.24 if light>.70 else max(.30,min(light,.55));sat=min(max(sat,.18),.55)
 elif role=='shadow':return '#020817'+alpha
 else:
  if light>.93:return '#111c2e'+alpha
  if light>.70:light=.16;sat=min(max(sat,.2),.5)
  elif light>.32:light=.27 if sat>.45 else .18;sat=min(sat,.72)
  else:light=max(.055,min(light,.13));sat=min(sat,.6)
 rgb=colorsys.hls_to_rgb(hue,light,sat)
 return '#'+''.join(f'{round(c*255):02x}' for c in rgb)+alpha
for file in ['app/globals.css','app/interactions.css','app/immersive.css']:
 path=Path(file);source=path.read_text()
 for role,raw in re.findall(r"var\(--tone-(fg|bg|line|shadow)-([0-9a-f]+),",source):
  palette[f"--tone-{role}-{raw}"]=adapt("#"+raw,role)
 def declaration(match):
  prop,value=match.group(1),match.group(2)
  if prop.startswith('--') or 'var(--tone-' in value or 'url(' in value:return match.group(0)
  if prop in ['color','fill','stroke','caret-color','text-decoration-color']:role='fg'
  elif 'shadow' in prop:role='shadow'
  elif any(x in prop for x in ['border','outline']):role='line'
  elif 'background' in prop:role='bg'
  else:return match.group(0)
  def token(m):
   original=m.group(0).lower();name=f'--tone-{role}-{original[1:]}';palette[name]=adapt(original,role)
   return f'var({name},{original})'
  return prop+':'+hex_re.sub(token,value)
 source=re.sub(r'([\w-]+)\s*:\s*([^;{}]+)',declaration,source)
 path.write_text(source)
Path('app/night-palette.css').write_text('/* Role-specific night equivalents for the existing light styles. Generated by scripts/design/theme-tokens.py. */\n.dark{\n'+''.join(f'  {k}:{v};\n' for k,v in sorted(palette.items()))+'}\n')
print('Created night equivalents:',len(palette))
