"use client";
import {useRef,useState,type PointerEvent} from "react";
import {AnimatePresence,motion,useReducedMotion} from "motion/react";
import {ArrowUpRight,ExternalLink,X,Play,ChevronLeft,ChevronRight} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from "@/components/ui/dialog";
import {SectionNavigator} from "@/components/section-navigator";
import {TechnologyDock} from "@/components/technology-dock";
import {showcaseProjects,type ShowcaseProject} from "@/lib/project-showcase";
import SpotlightCard from "@/components/react-bits/SpotlightCard";
import {gatehavenDemo} from "@/lib/gatehaven";

type Visual={src:string;alt:string;label:string;kind?:"video";poster?:string};
function mediaFor(p:ShowcaseProject):Visual[]{const media:Visual[]=[{src:p.image||`/logos/${p.slug}.png`,alt:p.imageAlt||`${p.name} project logo`,label:p.image?"Project view":"Identity"}];if(p.slug==="pro-competitive-programming")media.push({src:"/projects/pro-cp/dp.svg",alt:"Frog 1 dynamic programming example",label:"Dynamic programming"},{src:"/projects/pro-cp/fenwick.svg",alt:"Fenwick tree prefix sum diagram",label:"Range queries"});if(p.slug==="navox")media.push({src:"/projects/navox-walkthrough.mp4",alt:"NavoX sample-data walkthrough",label:"Watch demo",kind:"video"});if(p.slug==="fluxion")media.push({src:"/projects/fluxion-autograd.png",alt:"Fluxion autograd computation graph",label:"Autograd"});if(p.slug==="marketlab")media.push({src:"/projects/marketlab-stock-pipeline.svg",alt:"MarketLab stock data pipeline",label:"Stock pipeline"});if(p.slug==="gatehaven")media.push({src:gatehavenDemo,alt:"Gatehaven gameplay recording",label:"Watch gameplay",kind:"video",poster:"/projects/gatehaven/demo-poster.png"},{src:"/projects/gatehaven/components.png",alt:"Gatehaven gates, relays, crossings, screens, and file ports",label:"Components"},{src:"/projects/gatehaven/lessons.png",alt:"Gatehaven built-in circuit lessons",label:"Lessons"});return media;}
function ProjectGallery({project}:{project:ShowcaseProject}){const [index,setIndex]=useState(0);const media=mediaFor(project),active=media[index];return <div className="project-gallery"><div className="gallery-browser"><span aria-hidden="true"><i/><i/><i/></span><small>{project.name} / {active.label}</small></div><div className={`gallery-stage ${!project.image?"gallery-logo":""}`} key={active.src}>{active.kind==="video"?<video src={active.src} poster={active.poster} controls playsInline preload="metadata" aria-label={active.alt}/>:<a href={active.src} target="_blank" rel="noopener noreferrer" aria-label={`Open full-size ${active.alt}`}><img src={active.src} alt={active.alt} width={1400} height={800}/></a>}</div>{media.length>1&&<div className="gallery-controls"><button type="button" aria-label="Previous project visual" onClick={()=>setIndex(i=>(i+media.length-1)%media.length)}><ChevronLeft size={18}/></button><div role="group" aria-label="Project visuals">{media.map((m,i)=><button type="button" aria-pressed={i===index} key={m.src} onClick={()=>setIndex(i)}>{m.kind==="video"&&<Play size={13}/>}<span>{m.label}</span></button>)}</div><button type="button" aria-label="Next project visual" onClick={()=>setIndex(i=>(i+1)%media.length)}><ChevronRight size={18}/></button></div>}<p className="gallery-caption">{project.note}</p></div>;}
export function InteractiveProjects(){
 const [filter,setFilter]=useState("All projects"),[selected,setSelected]=useState<ShowcaseProject|null>(null);const trigger=useRef<HTMLButtonElement|null>(null),dialog=useRef<HTMLDivElement|null>(null);const reduced=useReducedMotion();const shown=showcaseProjects.filter(p=>filter==="All projects"||p.category===filter);
 function tilt(event:PointerEvent<HTMLElement>){if(reduced||event.pointerType!=="mouse")return;const r=event.currentTarget.getBoundingClientRect();const x=(event.clientX-r.left)/r.width-.5,y=(event.clientY-r.top)/r.height-.5;event.currentTarget.style.setProperty("--tilt-x",`${-y*6}deg`);event.currentTarget.style.setProperty("--tilt-y",`${x*6}deg`);event.currentTarget.style.setProperty("--spot-x",`${(x+.5)*100}%`);event.currentTarget.style.setProperty("--spot-y",`${(y+.5)*100}%`);}
 function reset(event:PointerEvent<HTMLElement>){event.currentTarget.style.setProperty("--tilt-x","0deg");event.currentTarget.style.setProperty("--tilt-y","0deg");}
 function select(p:ShowcaseProject,el:HTMLButtonElement){trigger.current=el;setSelected(p);}
 const switchProject=(delta:number)=>{if(!selected)return;const i=showcaseProjects.findIndex(p=>p.slug===selected.slug);setSelected(showcaseProjects[(i+delta+showcaseProjects.length)%showcaseProjects.length]);dialog.current?.scrollTo({top:0,behavior:"instant"});};
 return <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><section className="project-showcase" aria-label="Project collection"><div className="project-filter-row"><div className="project-filter-buttons" role="group" aria-label="Filter projects">{["All projects","AI & ML","Systems","Algorithms","Research","Collaboration"].map(c=><button type="button" key={c} onClick={()=>setFilter(c)} aria-pressed={filter===c}>{filter===c&&<motion.span layoutId="project-filter" className="filter-selection" transition={{duration:reduced?0:.25}}/>}<span>{c}</span></button>)}</div></div><motion.div layout={!reduced} className="showcase-grid"><AnimatePresence mode="popLayout">{shown.map((p,i)=><motion.article layout={!reduced} key={p.slug} initial={reduced?false:{opacity:0,y:24}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:reduced?1:.97}} transition={{duration:reduced?0:.35,delay:reduced?0:i*.035}} className={`showcase-card accent-${p.accent}`}><SpotlightCard className="showcase-card-inner" intensity={0.12} borderGlow={0.65} proximity={0} smoothing={0.25} onPointerMove={tilt} onPointerLeave={reset}><a href={`/projects/${p.slug}`} className={`showcase-visual ${p.cardLogo||!p.image?"is-logo":""} ${p.cardLogo?"has-brand-cover":""}`} aria-label={`Read the ${p.name} case study`}><span className="showcase-card-number mono">{p.category}</span><span className="showcase-image"><img src={p.cardLogo||p.image||`/logos/${p.slug}.png`} alt={p.cardLogo?`${p.name} logo`:p.imageAlt||`${p.name} logo`} width={p.cardLogo?512:1000} height={p.cardLogo?512:650} loading={i<3?"eager":"lazy"}/></span><span className="showcase-overlay"><strong>{p.name}</strong><span>{p.type}</span></span><span className="showcase-open" aria-hidden="true"><ArrowUpRight size={22}/></span></a><div className="showcase-card-detail"><p>{p.summary}</p><div className="showcase-card-links"><button type="button" onClick={e=>select(p,e.currentTarget)}>Quick preview <ArrowUpRight size={15}/></button><a href={`/projects/${p.slug}`} aria-label={`Read ${p.name} case study`}>Case study</a></div></div></SpotlightCard></motion.article>)}</AnimatePresence></motion.div><p className="showcase-footnote">Built, measured, documented. Select a project to look inside.</p></section>
 <DialogContent data-lenis-prevent data-section-scroll-root ref={dialog} className={`project-preview-dialog rich-project-dialog accent-${selected?.accent||"blue"}`} showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus();}}>{selected&&<><div className="preview-dialog-header"><div><img src={selected.logo||(selected.slug==="pro-competitive-programming"?"/tech/cplusplus.svg":`/logos/${selected.slug}.png`)} width={42} height={42} alt=""/><span className="mono">PROJECT</span></div><div className="preview-navigation"><button type="button" onClick={()=>switchProject(-1)} aria-label="Previous project"><ChevronLeft size={20}/></button><button type="button" onClick={()=>switchProject(1)} aria-label="Next project"><ChevronRight size={20}/></button><DialogClose asChild><button className="preview-close" aria-label="Close project preview"><X size={22}/></button></DialogClose></div></div><div className="rich-preview-heading"><div><span className="mono">{selected.type}</span><DialogTitle>{selected.name}<span>.</span></DialogTitle><DialogDescription>{selected.summary}</DialogDescription></div><a href={`/projects/${selected.slug}`} className="button-primary">Full case study<ArrowUpRight size={17}/></a></div><ProjectGallery key={selected.slug} project={selected}/><SectionNavigator key={`sections-${selected.slug}`} className="project-detail-tabs" label={`${selected.name} details`} sections={[{id:`preview-${selected.slug}-overview`,label:"Overview",content:<><p className="preview-overview">{selected.overview}</p><div className="preview-features">{selected.features.slice(0,3).map(f=><div key={f.title}><h3>{f.title}</h3><p>{f.text}</p></div>)}</div></>},{id:`preview-${selected.slug}-system`,label:"How it works",content:<><ol className="preview-system">{selected.stages.map(s=><li key={s.title}><div><h3>{s.title}</h3><p>{s.text}</p></div></li>)}</ol></>},{id:`preview-${selected.slug}-resources`,label:"Links & evidence",content:<><div className="preview-evidence"><strong>{selected.evidence}</strong><span>{selected.evidenceLabel}</span></div><div className="project-resource-list">{selected.resources.map(r=><a key={r.href} href={r.href} target="_blank" rel="noopener noreferrer"><span><small>{r.kind}</small><strong>{r.label}</strong></span><ExternalLink size={17}/></a>)}</div></>}]}/><div className="preview-toolkit"><span className="mono">BUILT WITH</span><TechnologyDock technologies={selected.stack}/></div><div className="rich-preview-footer">{selected.live&&<a href={selected.live} className="button-primary" target="_blank" rel="noopener noreferrer">Visit {selected.name}<ExternalLink size={16}/></a>}<a href={selected.repo} className="button-secondary" target="_blank" rel="noopener noreferrer">View source<ExternalLink size={16}/></a><a href={`/projects/${selected.slug}`} className="text-link">Read the complete story</a></div></>}</DialogContent></Dialog>;
}
