"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { usePathname } from "next/navigation";
import { Menu, Copy, Check, Code2, UserRound, Mail, ExternalLink } from "lucide-react";
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetClose } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { SectionNavigator } from "@/components/section-navigator";
import { competitiveProject } from "@/lib/competitive-programming";
import { projects, person, type Project } from "@/lib/portfolio";
import { details, type CaseSlug, type PipelineStep } from "@/lib/project-details";

export function ProjectMark({slug,name,className=""}:{slug:string;name:string;className?:string}) {
 return <img className={`project-mark ${className}`} src={slug==="pro-competitive-programming"?"/tech/cplusplus.svg":`/logos/${slug}.png`} width={96} height={96} alt={`${name} logo`} loading="lazy"/>;
}
const navigation=[["Work","/work"],["Research","/research"],["About","/about"],["Contact","/contact"]];
export function Navigation(){
 const pathname=usePathname();
 const active=(href:string)=>pathname===href||(href==="/about"&&pathname.startsWith("/about/"))||(href==="/work"&&pathname.startsWith("/projects/")&&pathname!=="/projects/toolret")||(href==="/research"&&pathname==="/projects/toolret");
 return <header className="site-nav"><a href="/" className="wordmark" aria-label="MBA~Steins — Michael Baffour Awuah home"><img src="/brand/mba-steins.png" alt="MBA~Steins" width={440} height={62} fetchPriority="high"/></a><nav aria-label="Main navigation" className="desktop-nav">{navigation.map(([name,href])=><a key={name} href={href} aria-current={active(href)?"page":undefined}>{name}</a>)}</nav><a className="nav-github" href={person.github} target="_blank" rel="noopener noreferrer"><Code2 size={18}/><span>GitHub</span></a><div className="mobile-nav"><Sheet><SheetTrigger asChild><button type="button" className="icon-button" aria-label="Open navigation"><Menu size={23}/></button></SheetTrigger><SheetContent className="mobile-sheet" aria-describedby={undefined}><SheetTitle>MBA~Steins</SheetTitle><SheetClose asChild><a href="/">Home</a></SheetClose>{navigation.map(([name,href])=><SheetClose asChild key={name}><a href={href} aria-current={active(href)?"page":undefined}>{name}</a></SheetClose>)}</SheetContent></Sheet></div></header>;
}
export function SystemsVisual(){
 return <div className="engineering-stage has-portrait"><div className="engineering-art"><img src="/engineering-loop.webp" width={1536} height={1024} alt="" aria-hidden="true"/></div><svg className="project-network" viewBox="0 0 720 610" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1"><path d="M130 105H255L350 285M600 185H495L350 285M125 420H245L350 285M595 450H465L350 285M350 285V490H160V555M350 490H560V555"/><circle cx="350" cy="285" r="53" strokeDasharray="3 7"/><circle cx="350" cy="285" r="210" strokeDasharray="1 10"/></g></svg><a className="landing-portrait" href="/about" aria-label="Meet Michael Baffour Awuah — read my story"><span className="portrait-corner portrait-corner-top" aria-hidden="true"/><span className="portrait-corner portrait-corner-bottom" aria-hidden="true"/><div className="landing-portrait-frame"><img src="/personal/michael-landing-atrium.webp" alt="Michael Baffour Awuah smiling in a decorated black suit and glasses" width={1147} height={1372} fetchPriority="high"/></div><div className="landing-portrait-caption"><span>Michael <small>MBA~STEINS</small></span><span className="portrait-story-link">My story <ExternalLink size={15}/></span></div></a><div className="hero-projects">{[...projects,competitiveProject].map(p=><a key={p.slug} href={`/projects/${p.slug}`} className={`network-node node-${p.slug}`} aria-label={`Open ${p.name} project`}><ProjectMark slug={p.slug} name={p.name}/><span>{p.name}<small>{p.category}</small></span></a>)}</div></div>;
}
export function PipelineExplorer({steps,name}:{steps:readonly PipelineStep[];name:string}){
 return <Tabs defaultValue="0" className="pipeline-explorer"><TabsList className="pipeline-stages" aria-label={`${name} pipeline stages`}>{steps.map((s,i)=><TabsTrigger key={s.title} value={String(i)}><strong>{s.title}</strong></TabsTrigger>)}</TabsList>{steps.map((s,i)=><TabsContent key={s.title} value={String(i)} className="pipeline-detail"><div><h3>{s.title}</h3><p>{s.text}</p></div></TabsContent>)}</Tabs>;
}
export function ProjectArchitecture({project}:{project:Project}){
 const stages=details[project.slug as CaseSlug].stages;
 return <div className={`architecture-display accent-${project.accent}`}><div className="architecture-heading"><span className="mono">{project.name} / SYSTEM MAP</span><ProjectMark slug={project.slug} name={project.name}/></div>{project.slug==="modelforge"?<svg viewBox="0 0 640 300" role="img" aria-label="An immutable artifact feeds stable and canary versions. Health gates determine promotion or rollback with stable fallback."><g className="arch-traces"><path d="M165 140H220V70H270M220 140v85h50M405 70h50v70h35M405 225h50v-85"/></g><g className="arch-box"><rect x="15" y="105" width="150" height="70" rx="12"/><rect x="270" y="35" width="135" height="70" rx="12"/><rect x="270" y="190" width="135" height="70" rx="12"/><rect x="490" y="105" width="135" height="70" rx="12"/></g><g className="arch-text"><text x="90" y="134">Artifact</text><text className="arch-small" x="90" y="155">SHA-256</text><text x="337" y="76">Stable</text><text x="337" y="231">Canary</text><text x="557" y="145">Health gate</text></g></svg>:<div className="compact-system">{stages.slice(0,4).map(s=><div key={s.title}><strong>{s.title}</strong></div>)}</div>}<p className="architecture-caption">{project.slug==="modelforge"?"Register · canary · promote or recover":project.summary}</p></div>;
}
export function ProjectGallery(){
 const categories=["All projects","AI & ML","Systems"];const work=projects.filter(p=>p.category!=="Research");
 return <Tabs defaultValue="All projects" className="work-tabs"><TabsList className="filter-tabs" aria-label="Filter projects">{categories.map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList>{categories.map(c=><TabsContent key={c} value={c}><div className="project-grid">{work.filter(p=>c==="All projects"||p.category===c).map(p=><a href={`/projects/${p.slug}`} key={p.slug} className={`project-card accent-${p.accent}`}><div className="project-card-top"><ProjectMark slug={p.slug} name={p.name}/><span className="mono">{p.category}</span><ExternalLink size={18}/></div><div className="project-card-visual">{p.image?<img src={p.image} alt={p.imageAlt} width={1200} height={700} loading="lazy"/>:<ProjectArchitecture project={p}/>}</div><div className="project-card-copy"><span className="mono">{p.type}</span><h2>{p.name}<span className="project-open">Open project</span></h2><p>{p.description}</p><div className="card-bottom"><span>{p.evidence}</span><span>Case study</span></div></div></a>)}</div></TabsContent>)}</Tabs>;
}
export function CaseNotebook({overview,system,evidence,resources,labels=["Overview","How it works","Evidence","Code & documents"]}:{overview:ReactNode;system:ReactNode;evidence:ReactNode;resources:ReactNode;labels?:readonly [string,string,string,string]}){
 const sections=[{id:"overview",label:labels[0],content:overview},{id:"system",label:labels[1],content:system},{id:"evidence",label:labels[2],content:evidence},{id:"resources",label:labels[3],content:resources}];
 return <SectionNavigator sections={sections} className="case-notebook" label="Project details"/>;
}
export function ResearchComparison(){
 return <div className="research-comparison"><p className="mono">CROSS-ENCODER CALLS · 1,500 QUERIES</p><div className="comparison-row"><div><span>Always rerank</span><b>1,500</b></div><div className="comparison-track"><span style={{width:"100%"}}/></div></div><div className="comparison-row routed"><div><span>Conditional router</span><b>1,149</b></div><div className="comparison-track"><span style={{width:"76.6%"}}/></div></div><p className="comparison-caption">351 fewer calls on untouched confirmation queries.</p></div>;
}
export function ContactLinks(){
 const [copied,setCopied]=useState(false);const [failed,setFailed]=useState(false);const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timeout.current)clearTimeout(timeout.current);},[]);
 async function copy(){try{await navigator.clipboard.writeText(person.email);setCopied(true);setFailed(false);if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>setCopied(false),2500);}catch{setFailed(true);}}
 return <div className="contact-links"><a className="contact-email" href={`mailto:${person.email}`}><Mail size={25}/><span>{person.email}</span></a><button className="copy-email" onClick={copy} type="button" aria-label="Copy email address">{copied?<Check size={18}/>:<Copy size={18}/>}<span aria-live="polite">{copied?"Copied":"Copy email"}</span></button>{failed&&<p role="status">Please select and copy the email address above.</p>}<div className="social-links"><a href={person.github} target="_blank" rel="noopener noreferrer"><Code2 size={21}/><span>GitHub<small>Code, projects & experiments</small></span><ExternalLink size={17}/></a><a href={person.linkedin} target="_blank" rel="noopener noreferrer"><UserRound size={21}/><span>LinkedIn<small>Experience & professional profile</small></span><ExternalLink size={17}/></a></div></div>;
}
