"use client";

import { useEffect, useState } from "react";
import { toolkit, type ToolkitId } from "@/lib/toolkit";
import { projects } from "@/lib/portfolio";

export function SkillsKeyboard(){
 const [selected,setSelected]=useState<ToolkitId>("ts");
 useEffect(()=>{window.dispatchEvent(new CustomEvent("portfolio:toolkit",{detail:selected}));},[selected]);
 const current=toolkit.find(t=>t.id===selected)!;
 return <section className="toolkit-showcase" data-keyboard-scene="skills" data-selected-tool={selected} aria-labelledby="toolkit-heading"><div className="toolkit-heading"><div><span className="mono">THE ENGINEERING TOOLKIT</span><h2 id="toolkit-heading">Tools with a purpose.</h2></div><p>Select a technology to see where it fits in my work.</p></div><div className="toolkit-selector" role="group" aria-label="Explore technology usage">{toolkit.map(t=><button type="button" aria-pressed={selected===t.id} key={t.id} onClick={()=>setSelected(t.id)} onPointerEnter={e=>{if(e.pointerType==="mouse")setSelected(t.id);}} onFocus={()=>setSelected(t.id)}><img src={`/tech/${t.icon}.svg`} width={24} height={24} alt=""/>{t.name}</button>)}</div><div className="toolkit-stage-grid"><div className="toolkit-scene toolkit-html-scene" data-keyboard-window><div className="toolkit-scene-label"><span className="mono">INTERFACE / SYSTEM / INFRASTRUCTURE</span></div><div className="toolkit-fallback">{toolkit.slice(0,9).map(t=><button key={t.id} type="button" aria-label={`Explore ${t.name}`} aria-pressed={selected===t.id} onClick={()=>setSelected(t.id)} onPointerEnter={e=>{if(e.pointerType==="mouse")setSelected(t.id);}} onFocus={()=>setSelected(t.id)}><img src={`/tech/${t.icon}.svg`} width={40} height={40} alt=""/><strong>{t.name}</strong></button>)}</div><div className="toolkit-scene-bottom"><span>Choose a tool. Explore the work behind it.</span></div></div><div className="toolkit-detail" aria-live="polite" aria-atomic="true"><span className="mono">{current.group}</span><img className="toolkit-detail-icon" src={`/tech/${current.icon}.svg`} alt="" width={58} height={58}/><h3>{current.name}</h3><p>{current.description}</p><span className="mono toolkit-used-label">USED IN MY WORK</span><div className="toolkit-project-links">{current.projects.map(slug=>{const name=projects.find(p=>p.slug===slug)?.name||"SlopeChat";return <a href={`/projects/${slug}`} key={slug}><img src={`/logos/${slug}.png`} width={28} height={28} alt=""/>{name}</a>;})}</div></div></div><p className="keyboard-credit">Keyboard scene adapted from <a href="https://github.com/kpeis695/personal-website" target="_blank" rel="noopener noreferrer">Sylvester Kpei</a>.</p></section>;
}
