import { projects } from "@/lib/portfolio";
import { details, type CaseSlug } from "@/lib/project-details";
import { competitiveProject } from "@/lib/competitive-programming";
import { gatehavenProject } from "@/lib/gatehaven";
export type ShowcaseProject={slug:string;name:string;type:string;platforms?:readonly string[];category:string;accent:string;number:string;summary:string;description:string;image:string;imageAlt:string;logo?:string;cardLogo?:string;stack:readonly string[];repo:string;live:string;evidence:string;evidenceLabel:string;note:string;overview:string;features:readonly {title:string;text:string}[];resources:readonly {label:string;href:string;kind:string}[];stages:readonly {title:string;text:string}[]};
const order=["navox","fluxion","modelforge","marketlab","toolret"];
export const showcaseProjects:ShowcaseProject[]=order.map(slug=>{const p=projects.find(p=>p.slug===slug)!;const d=details[slug as CaseSlug];return {...p,cardLogo:slug==="navox"||slug==="marketlab"?`/logos/${slug}.png`:undefined,overview:d.overview,features:d.features,resources:d.resources,stages:d.stages};});
showcaseProjects.push({slug:"slopechat",name:"SlopeChat",type:"Campus social app",category:"Collaboration",accent:"red",number:"06",summary:"Meet beyond your circle.",description:"A social video-chat app we started with a simple idea: help university students meet beyond their usual circle.",image:"/projects/slopechat-video-call.webp",imageAlt:"Illustrative video-call photography used on SlopeChat’s landing page",stack:["TypeScript","React","Next.js","Supabase","WebRTC"],repo:"https://github.com/Beechamp2019/slopechat",live:"https://slopechat.com/",evidence:"UI/UX & frontend developer",evidenceLabel:"Collaborative project",note:"Illustrative photography from SlopeChat’s landing page. My work focused on the design and frontend experience.",overview:"One day, a friend and I sat down and decided to create SlopeChat. University puts you around thousands of people, but meeting someone outside your usual circle still takes a first step. We wanted to make that step easier through shared interests and one-to-one video conversations.",features:[{title:"Find common ground",text:"Choose interests to give a first conversation somewhere to start."},{title:"Meet face-to-face",text:"Prepare your camera and microphone, then connect with another student."},{title:"My contribution",text:"UI/UX and frontend redesign across the landing page, sign-in, interests, camera setup, matching, friends, and call screens."}],stages:[{title:"Verify",text:"Start with university email verification."},{title:"Choose interests",text:"Find common ground before a first hello."},{title:"Get ready",text:"Preview your camera and microphone."},{title:"Connect",text:"Meet another student through one-to-one video."}],resources:[{label:"Visit SlopeChat",href:"https://slopechat.com/",kind:"live"},{label:"Project source",href:"https://github.com/Beechamp2019/slopechat",kind:"source"}]});

showcaseProjects.splice(2,0,gatehavenProject);
showcaseProjects.push(competitiveProject);
