export const toolkit = [
 {id:"ts",sceneDescription:"Typed interfaces and application logic.",name:"TypeScript",icon:"typescript",group:"Interfaces",description:"Typed interfaces and application logic, from a conversational assistant to inspectable portfolio research.",projects:["navox","marketlab"]},
 {id:"react",sceneDescription:"Responsive, component-based interfaces.",name:"React",icon:"react",group:"Interfaces",description:"Component-based interfaces that make complex tools understandable and keep interactions responsive.",projects:["navox","marketlab","slopechat"]},
 {id:"nextjs",sceneDescription:"Web applications and product interfaces.",name:"Next.js",icon:"nextjs",group:"Interfaces",description:"Web application structure and product interfaces for NavoX and the SlopeChat collaboration.",projects:["navox","slopechat"]},
 {id:"python",sceneDescription:"Autograd, retrieval experiments, and APIs.",name:"Python",icon:"python",group:"AI & systems",description:"Autograd, retrieval experiments, API services, and independent replay of financial calculations.",projects:["fluxion","toolret","navox","marketlab"]},
 {id:"pytorch",sceneDescription:"Independent model and gradient checks.",name:"PyTorch",icon:"pytorch",group:"AI & systems",description:"Independent output and gradient checks for Fluxion, retrieval research, and model execution in ModelForge.",projects:["fluxion","toolret","modelforge"]},
 {id:"cpp",sceneDescription:"Native numerical and risk calculations.",name:"C++",icon:"cplusplus",group:"AI & systems",description:"Native Linear and BLAS experiments in Fluxion, plus independently checked risk calculations in MarketLab.",projects:["fluxion","marketlab"]},
 {id:"postgres",sceneDescription:"Structured data and account boundaries.",name:"PostgreSQL",icon:"postgresql",group:"Infrastructure",description:"Structured application data and account boundaries in the NavoX backend.",projects:["navox"]},
 {id:"mongodb",sceneDescription:"Owner-scoped research data and worker jobs.",name:"MongoDB",icon:"mongodb",group:"Infrastructure",description:"Owner-scoped research records and fenced background work in the MarketLab research service.",projects:["marketlab"]},
 {id:"docker",sceneDescription:"Reproducible services and model workflows.",name:"Docker",icon:"docker",group:"Infrastructure",description:"Reproducible services and containerized validation for assistants and model deployment workflows.",projects:["navox","modelforge"]},
 {id:"go",sceneDescription:"Model execution and deployment architecture.",name:"Go",icon:"go",group:"AI & systems",description:"A runtime option in ModelForge’s model execution and deployment architecture.",projects:["modelforge"]},
 {id:"fastapi",sceneDescription:"Python APIs for products and model workflows.",name:"FastAPI",icon:"fastapi",group:"AI & systems",description:"Python API services connecting product interfaces with backend and model workflows.",projects:["navox","modelforge"]},
 {id:"aws",sceneDescription:"Reference model deployment infrastructure.",name:"AWS",icon:"amazonwebservices",group:"Infrastructure",description:"Reference infrastructure configuration for ModelForge; the repository records the deployment design and its limits.",projects:["modelforge"]},
] as const;
export type ToolkitId = (typeof toolkit)[number]["id"];
